CREATE TABLE Questions (
    qid INT AUTO_INCREMENT PRIMARY KEY,
    qtext TEXT NOT NULL
);
INSERT INTO Questions (qtext) 
VALUES 
('When the phone rings, you hurry to get to it first and don\'t hope someone else gets it.'),
('You are more observant than introspective.'),
('Is it worse to have your head in the clouds than to be in a rut?'),
('With people, you are usually more firm than gentle.'),
('You are more comfortable making critical judgments than value judgments.'),
('Clutter in the workplace is something you take time to straighten up rather than tolerate pretty well.'),
('It is your way to make up your mind quickly.'),
('Waiting in line, you often chat with others.'),
('You are more sensible than ideational.'),
('You are more interested in what is actual than what is possible.'),
('In making up your mind, you are more likely to go by data than desires.'),
('In sizing up others, you tend to be more objective and impersonal than friendly and personal.'),
('You prefer contracts to be signed, sealed, and delivered rather than settled on a handshake.'),
('You are more satisfied having a finished product than a work in progress.'),
('At a party, you interact with many, even strangers, rather than interact with a few friends.'),
('You tend to be more factual than speculative.'),
('You like writers who say what they mean rather than use metaphors and symbolism.'),
('Consistency of thought appeals more than harmonious relationships.'),
('When disappointing someone, you are more frank and forthright than warm and considerate.'),
('On the job, you want your activities scheduled.'),
('You more often prefer final, unalterable statements to tentative, preliminary statements.'),
('Interacting with strangers energizes you more than it taxes your reserves.'),
('Facts speak for themselves rather than illustrate principles.'),
('You find visionaries and theorists more annoying than fascinating.'),
('In a heated discussion, you stick to your guns and don\'t look for common ground.'),
('It is better to be just than merciful.'),
('At work, it is more natural for you to point out mistakes than try to please others.'),
('You are more comfortable after a decision than before.'),
('You tend to say right out what\'s on your mind more than keep your ears open.'),
('Common sense is usually more reliable than frequently questionable.'),
('Children should make themselves more useful rather than exercise their fantasy.'),
('When in charge of others, you tend to be more firm and unbending than forgiving and lenient.'),
('You are more often a cool-headed person rather than warm-hearted.'),
('You are more prone to nailing things down than exploring the possibilities.'),
('In most situations, are you more deliberate than spontaneous?'),
('You think of yourself as more outgoing than private.'),
('You are more frequently a practical sort of person and not fanciful.'),
('You speak more in particulars than generalities.'),
('Being called a logical person is more of a compliment than being called sentimental.'),
('Your thoughts rule you more than your feelings.'),
('When finishing a job, you\'d rather tie up loose ends than move on to something else.'),
('You rather work to deadlines than just whenever.'),
('You are more the talkative kind of person than one who doesn\'t miss much.'),
('You are inclined to take what is said more literally than figuratively.'),
('You more often see what is right in front of you than what can only be imagined.'),
('Is it worse to be a softy than hard-nosed?'),
('In trying circumstances, you are more too unsympathetic than sympathetic.'),
('You tend to choose more carefully than impulsively.'),
('You are inclined to be more hurried than leisurely.'),
('At work, you tend to be more sociable with colleagues than keeping to yourself.'),
('You are more likely to trust your experiences than your conceptions.'),
('You are more inclined to feel down to earth than somewhat removed.'),
('You think of yourself as more tough-minded than tender-hearted.'),
('You value in yourself more that you are reasonable rather than devoted.'),
('You usually want things more settled and decided than just penciled in.'),
('You are more serious and determined than you are easygoing.'),
('You consider yourself a better conversationalist than a good listener.'),
('You prize in yourself your strong hold on reality over your vivid imagination.'),
('You are drawn more to fundamentals than overtones.'),
('It is a greater fault to be too compassionate than too dispassionate.'),
('You are swayed more by convincing evidence than a touching appeal.'),
('You feel better about coming to closure than keeping your options open.'),
('Is it preferable mostly to make sure things are arranged rather than let things happen naturally?'),
('You are inclined to be more easy to approach than somewhat reserved.'),
('In stories, you prefer action and adventure to fantasy and heroism.'),
('Is it easier for you to put others to good use than identify with others?'),
('You wish strength of will for yourself more than strength of emotion.'),
('You are more thick-skinned than thin-skinned.'),
('You tend to notice disorderliness more than opportunities for change.'),
('You are more routine than whimsical.');
  

CREATE TABLE RESPONCES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userid INT NOT NULL,
    question_responce JSON NOT NULL,
    FOREIGN KEY (userid) REFERENCES users(id) ON DELETE CASCADE
)



